# Generated by Django 5.1.7 on 2026-02-28 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('booking', '0005_alter_user_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemevent',
            options={'ordering': ['-timestamp'], 'verbose_name': 'System Event', 'verbose_name_plural': 'System Events'},
        ),
        migrations.AddField(
            model_name='systemevent',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_events', to='booking.computerbooking'),
        ),
        migrations.AddField(
            model_name='systemevent',
            name='message',
            field=models.TextField(default='message'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemevent',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemevent',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemevent',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemevent',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_events', to='booking.labsession'),
        ),
        migrations.AddField(
            model_name='systemevent',
            name='severity',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='systemevent',
            name='event_type',
            field=models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('registration', 'User Registration'), ('booking_created', 'Booking Created'), ('booking_approved', 'Booking Approved'), ('booking_rejected', 'Booking Rejected'), ('booking_cancelled', 'Booking Cancelled'), ('session_created', 'Lab Session Created'), ('session_approved', 'Lab Session Approved'), ('session_rejected', 'Lab Session Rejected'), ('maintenance_request', 'Maintenance Request'), ('maintenance_resolved', 'Maintenance Resolved'), ('system_error', 'System Error'), ('security_alert', 'Security Alert'), ('password_change', 'Password Changed'), ('permission_change', 'Permission Changed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='systemevent',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='systemevent',
            index=models.Index(fields=['event_type', 'timestamp'], name='analytics_s_event_t_72281e_idx'),
        ),
        migrations.AddIndex(
            model_name='systemevent',
            index=models.Index(fields=['user', 'timestamp'], name='analytics_s_user_id_f08c6a_idx'),
        ),
        migrations.AddIndex(
            model_name='systemevent',
            index=models.Index(fields=['severity', 'resolved'], name='analytics_s_severit_f5f557_idx'),
        ),
        migrations.AddIndex(
            model_name='systemevent',
            index=models.Index(fields=['resolved'], name='analytics_s_resolve_54425d_idx'),
        ),
    ]
