# Generated by Django 5.1.7 on 2026-02-28 23:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('html_content', models.TextField(help_text='HTML content for the email')),
                ('text_content', models.TextField(help_text="Plain text version (for email clients that don't support HTML)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('receive_updates', models.BooleanField(default=True, help_text='System updates and improvements')),
                ('receive_lab_news', models.BooleanField(default=True, help_text='News about lab facilities and availability')),
                ('receive_tips', models.BooleanField(default=False, help_text='Tips and best practices for using labs')),
                ('receive_events', models.BooleanField(default=False, help_text='Lab workshops and special events')),
                ('is_active', models.BooleanField(default=True)),
                ('unsubscribe_token', models.CharField(max_length=255, unique=True)),
                ('source', models.CharField(choices=[('main', 'Main Newsletter Form'), ('footer', 'Footer Form'), ('popup', 'Popup Form'), ('import', 'CSV Import'), ('admin', 'Admin Added'), ('other', 'Other Source')], default='main', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscription',
                'verbose_name_plural': 'Newsletter Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('custom_html_content', models.TextField(blank=True, help_text='Custom HTML content (if not using template)')),
                ('custom_text_content', models.TextField(blank=True, help_text='Custom plain text content (if not using template)')),
                ('recipient_type', models.CharField(choices=[('all_users', 'All System Users'), ('students', 'Student Users Only'), ('lecturers', 'Lecturers Only'), ('admins', 'Administrators Only'), ('subscribers', 'Newsletter Subscribers'), ('csv_upload', 'CSV Upload Recipients')], default='all_users', max_length=20)),
                ('sender_email', models.EmailField(blank=True, help_text='Sender email address (if different from default)', max_length=254)),
                ('csv_file', models.FileField(blank=True, help_text='CSV file with recipient data', null=True, upload_to='email_campaigns/csv/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_recipients', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('open_count', models.IntegerField(default=0)),
                ('click_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_email_campaigns', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsletter.emailtemplate')),
            ],
            options={
                'verbose_name': 'Email Campaign',
                'verbose_name_plural': 'Email Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced')], default='pending', max_length=10)),
                ('tracking_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='newsletter.emailcampaign')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Email deliveries',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='CsvRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('data', models.JSONField(default=dict, help_text='Additional data from CSV for placeholders')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_recipients', to='newsletter.emailcampaign')),
            ],
            options={
                'ordering': ['email'],
                'unique_together': {('campaign', 'email')},
            },
        ),
    ]
