# Generated by Django 5.1.7 on 2025-05-22 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_notification_booking_notification_lab_session_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemEvent',
        ),
    ]
