# Generated by Django 5.1.7 on 2026-02-28 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_delete_systemevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
        migrations.AddField(
            model_name='computerbooking',
            name='approval_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='computerbooking',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computerbooking',
            name='cancellation_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='computerbooking',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='computerbooking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computerbooking',
            name='extension_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='computerbooking',
            name='extension_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computerbooking',
            name='extension_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='computerbooking',
            name='extension_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computerbooking',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computerbooking',
            name='rejection_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='computerbooking',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labsession',
            name='approval_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labsession',
            name='attending_students',
            field=models.ManyToManyField(blank=True, related_name='attending_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labsession',
            name='cancellation_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labsession',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='labsession',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labsession',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labsession',
            name='rejection_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_super_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='managed_labs',
            field=models.ManyToManyField(blank=True, related_name='lab_admins', to='booking.lab'),
        ),
        migrations.AddField(
            model_name='user',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.'), ('Eng.', 'Eng.'), ('Hon.', 'Hon.'), ('', 'None')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(blank=True, choices=[('SSI', 'School of Science and Informatics'), ('SBAESS', 'School of Business Administration and Economic Social Sciences'), ('SME', 'School of Mining and Engineering'), ('SoE', 'School of Education'), ('SAEES', 'School of Agriculture, Environment and Earth Sciences')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_booking', 'New Booking'), ('booking_cancelled', 'Booking Cancelled'), ('session_booked', 'Session Booked'), ('booking_approved', 'Booking Approved'), ('booking_rejected', 'Booking Rejected'), ('recurring_session_created', 'Recurring Session Created'), ('recurring_session_approved', 'Recurring Session Approved'), ('recurring_session_rejected', 'Recurring Session Rejected'), ('booking_ending', 'Booking Ending Soon'), ('booking_extended', 'Booking Extended'), ('extension_unavailable', 'Extension Unavailable'), ('checkin_reminder', 'Check-in Reminder'), ('attendance_marked', 'Attendance Marked'), ('attendance_updated', 'Attendance Updated'), ('session_cancelled', 'Session Cancelled')], max_length=50),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('description', models.TextField(blank=True, help_text='Short summary for email subject')),
                ('priority', models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('target_students', models.BooleanField(default=True, help_text='Include all students')),
                ('target_lecturers', models.BooleanField(default=True, help_text='Include all lecturers')),
                ('target_admins', models.BooleanField(default=True, help_text='Include all admins')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='When to send the announcement', null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When to remove from feed', null=True)),
                ('send_email', models.BooleanField(default=True, help_text='Send email to recipients')),
                ('in_app_only', models.BooleanField(default=False, help_text='Only show in-app notification')),
                ('notifications_sent', models.IntegerField(default=0)),
                ('emails_sent', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
                ('target_users', models.ManyToManyField(blank=True, help_text='Leave empty to send to all users', related_name='received_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComputerBookingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], default='absent', max_length=10)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='booking.computerbooking')),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabAdministrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_admin_roles', to=settings.AUTH_USER_MODEL)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_assignments', to='booking.lab')),
            ],
            options={
                'verbose_name': 'Lab Administrator',
                'verbose_name_plural': 'Lab Administrators',
                'unique_together': {('admin', 'lab')},
            },
        ),
        migrations.CreateModel(
            name='SessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], default='absent', max_length=10)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_checks', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='booking.labsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('session', 'student')},
            },
        ),
        migrations.CreateModel(
            name='StudentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_ratings', to='booking.computerbooking')),
                ('rated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_ratings', to='booking.labsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('booking__isnull', True), ('session__isnull', False)), models.Q(('booking__isnull', False), ('session__isnull', True)), _connector='OR'), name='rating_has_either_session_or_booking')],
                'unique_together': {('student', 'rated_by', 'booking'), ('student', 'rated_by', 'session')},
            },
        ),
    ]
