# Generated by Django 5.1.7 on 2026-02-28 23:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general', 'General Feedback'), ('bug', 'Bug Report'), ('feature', 'Feature Request'), ('usability', 'Usability Issue'), ('experience', 'User Experience')], max_length=20)),
                ('message', models.TextField()),
                ('rating', models.IntegerField(blank=True, choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - Excellent')], null=True)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_addressed', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True)),
                ('page_url', models.CharField(blank=True, help_text='URL where feedback was submitted from', max_length=255)),
            ],
            options={
                'verbose_name': 'Anonymous Feedback',
                'verbose_name_plural': 'Anonymous Feedback',
                'ordering': ['-submission_date'],
            },
        ),
        migrations.CreateModel(
            name='DocumentationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order of this section')),
                ('content', models.TextField(blank=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Documentation Section',
                'verbose_name_plural': 'Documentation Sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SystemVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(help_text='Format: x.y.z (e.g., 1.0.0)', max_length=20, unique=True)),
                ('version_name', models.CharField(blank=True, help_text='Optional name for this version', max_length=100)),
                ('version_type', models.CharField(choices=[('major', 'Major Release'), ('minor', 'Minor Release'), ('patch', 'Patch/Bugfix')], default='patch', max_length=10)),
                ('release_date', models.DateField()),
                ('is_current', models.BooleanField(default=False, help_text='Is this the current active version?')),
                ('release_notes', models.TextField(blank=True)),
                ('developer', models.CharField(default='TTU IT Department', max_length=100)),
            ],
            options={
                'verbose_name': 'System Version',
                'verbose_name_plural': 'System Versions',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('additional_info', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='resources.documentationsection')),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('content', models.TextField(blank=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='resources.documentationsection')),
            ],
            options={
                'verbose_name': 'Documentation Subsection',
                'verbose_name_plural': 'Documentation Subsections',
                'ordering': ['section__order', 'order'],
                'unique_together': {('section', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='DocumentationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='resources.subsection')),
            ],
            options={
                'verbose_name': 'Documentation Item',
                'verbose_name_plural': 'Documentation Items',
                'ordering': ['subsection__section__order', 'subsection__order', 'order'],
            },
        ),
    ]
